apiVersion: v1
kind: Service
metadata:
  name: xian-springboot-k8s
spec:
  selector:
    app: xian-springboot-k8s
  ports:
    - protocol: TCP
      port: 80
      targetPort: 9090
  type: LoadBalancer